packages:
  - 'apps/*'
  - 'libs/*'
  - 'libs/*/*'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  less: true
  msgpackr-extract: true
  prisma: true
  unrs-resolver: true
