/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountOrdersIdRouteImport } from './routes/account/orders/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/account/orders/',
  path: '/account/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/account/orders/$id',
  path: '/account/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/catalog/': typeof CatalogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/catalog': typeof CatalogIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/catalog/': typeof CatalogIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/login'
    | '/register'
    | '/checkout/success'
    | '/products/$slug'
    | '/catalog/'
    | '/checkout/'
    | '/account/orders/$id'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/login'
    | '/register'
    | '/checkout/success'
    | '/products/$slug'
    | '/catalog'
    | '/checkout'
    | '/account/orders/$id'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/login'
    | '/register'
    | '/checkout/success'
    | '/products/$slug'
    | '/catalog/'
    | '/checkout/'
    | '/account/orders/$id'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/account/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/account/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
